<?php

/*
|--------------------------------------------------------------------------
| Calendar Language Lines / DE
|--------------------------------------------------------------------------
|         _________  _______          _       ____  _____  ________
|        |  _   _  ||_   __ \        / \     |_   \|_   _||_   __  |
|        |_/ | | \_|  | |__) |      / _ \      |   \ | |    | |_ \_|
|            | |      |  __ /      / ___ \     | |\ \| |    |  _| _
|           _| |_    _| |  \ \_  _/ /   \ \_  _| |_\   |_  _| |__/ |
|          |_____|  |____| |___||____| |____||_____|\____||________|
|                                                      by custura.de
*/

return [
    'approved_at' => 'Approved At',
    'approved_by' => 'Approved By',
    'are_you_sure_update?' => 'Are you sure you would like to update this Appointment?',
    'blue' => 'Blue',
    'cancel' => 'Cancel',
    'clients' => 'Clients',
    'color' => 'Color',
    'colors' => 'Colors',
    'confirm' => 'Confirm',
    'create' => 'Create',
    'created_at' => 'Created At',
    'created_by' => 'Created By',
    'created_successfully' => 'Created successfully',
    'date_is_in_future' => 'Date is in future.',
    'date_range_is_locked' => 'Date range is locked.',
    'day_total' => 'Day Total',
    'delete' => 'Delete',
    'details' => 'Details',
    'details_regrading_the_appointment' => 'Details regarding the appointment.',
    'disapproved_at' => 'Disapproved At',
    'disapproved_by' => 'Disapproved By',
    'duration' => 'Duration',
    'duration_important' => 'Important: For duration must from beginning to the end of shift.',
    'edit' => 'Edit',
    'end_at' => 'End At',
    'friday' => 'Friday',
    'holiday' => 'Holiday',
    'medical' => 'Medical',
    'monday' => 'Monday',
    'month' => 'Month',
    'month_total' => 'Month Total',
    'monthly_quotas' => 'Monthly Quotas',
    'no_notes' => 'There is no notes.',
    'no_permission' => 'You don\'t have permission.',
    'no_title' => 'There is no title.',
    'not_approved' => 'Not Approved',
    'not_provided' => 'Not Provided',
    'notes' => 'Notes',
    'orange' => 'Orange',
    'over_balance' => 'Over Balance',
    'over_quota' => 'Over Quota',
    'overlapping_records_are_not_allowed' => 'Overlapping records are not allowed.',
    'pause' => 'Pause',
    'projects' => 'Projects',
    'quota' => 'Quota',
    'red' => 'Red',
    'remaining_balance' => 'Remaining Balance',
    'remaining_quota' => 'Remaining Quota',
    'saturday' => 'Saturday',
    'save' => 'Save',
    'scheduled_at' => 'Scheduled At',
    'select_client' => 'Select Client',
    'select_color' => 'Select Color',
    'select_project' => 'Select Project',
    'select_task' => 'Select Task',
    'select_template' => 'Select Template',
    'set_to_day' => 'Set it to selected Day',
    'show_more' => 'Show More',
    'start_at' => 'Start At',
    'sunday' => 'Sunday',
    'tasks' => 'Tasks',
    'templates' => 'Templates',
    'this_action_is_unauthorized_on' => 'This action is unauthorized on ',
    'this_action_is_unauthorized_on_approved_appointment' => 'This action is unauthorized on approved appointment.',
    'thursday' => 'Thursday',
    'today' => 'Today',
    'tuesday' => 'Tuesday',
    'uncompleted' => 'UNCOMPLETED',
    'unschedule' => 'Unschedule',
    'unscheduled_events' => 'Unscheduled Events',
    'update' => 'Update',
    'update_appointment' => 'Update Appointment',
    'updated_at' => 'Updated At',
    'updated_successfully' => 'Updated successfully',
    'vacation' => 'Vacation',
    'wednesday' => 'Wednesday',
    'week_total' => 'Week Total',
    'work' => 'Work',
    'worked_time' => 'Worked Time',
    'year' => 'Year',
    'yellow' => 'Yellow',
];
