<?php

/*
|--------------------------------------------------------------------------
| Ticket Language Lines / DE
|--------------------------------------------------------------------------
|         _________  _______          _       ____  _____  ________
|        |  _   _  ||_   __ \        / \     |_   \|_   _||_   __  |
|        |_/ | | \_|  | |__) |      / _ \      |   \ | |    | |_ \_|
|            | |      |  __ /      / ___ \     | |\ \| |    |  _| _
|           _| |_    _| |  \ \_  _/ /   \ \_  _| |_\   |_  _| |__/ |
|          |_____|  |____| |___||____| |____||_____|\____||________|
|                                                      by custura.de
*/

return [
    'actions' => 'Actions',
    'agent' => 'Agent',
    'agent_roles' => 'Agent Roles',
    'all_tickets' => 'All Tickets',
    'all_tickets_description' => 'Here you can see or take any existing tickets.',
    'approved' => 'Approved',
    'are_you_sure_category' => 'Are you sure you would like to delete this category?',
    'are_you_sure_priority' => 'Are you sure you would like to delete this priority?',
    'are_you_sure_you_wold_like_to_recive_this_ticket' => 'Are you sure you would like to recive this Ticket?',
    'by' => 'by',
    'cancel' => 'Cancel',
    'category' => 'Category',
    'category_edit' => 'Category Edit',
    'create' => 'Create',
    'create_a_new_ticket' => 'Create a new ticket',
    'create_category' => 'Create Category',
    'create_category_description' => 'Create a new support ticket category.',
    'create_priority' => 'Create Priority',
    'create_priority_description' => 'Create a new support ticket priority.',
    'create_ticket' => 'Create Ticket',
    'create_ticket_description' => 'Create a new support ticket.',
    'created' => 'Created',
    'delete' => 'Delete',
    'delete_category' => 'Delete Category',
    'delete_priority' => 'Delete Priority',
    'deleted' => 'Deleted',
    'description' => 'Description',
    'disapproved' => 'Disapproved',
    'don\'_worry' => 'don\'t worry, just take a deep breath & say "Hello"',
    'fail_keyword' => 'No tickets found matching your search keyword',
    'file_upload' => 'File Upload',
    'language' => 'Language',
    'link_to_ticket' => 'Link To Ticket',
    'location' => 'Location',
    'manage_category' => 'Manage Category',
    'manage_category_description' => 'Here you can modify the existing categories.',
    'manage_priority' => 'Manage Priority',
    'manage_priority_description' => 'Here you can modify the existing priorities.',
    'manage_recived_tickets' => 'Manage Recived Tickets',
    'manage_recived_tickets_description' => 'Here you can manage existing tickets belongs to you.',
    'mark' => 'Mark',
    'member_since' => 'Member Since',
    'name' => 'Name',
    'no_message_yet' => 'No message yet...',
    'no_tickets_in_database' => 'No tickets in the database',
    'priority' => 'Priority',
    'priority_edit' => 'Priority Edit',
    'reopen' => 'Reopen',
    'save' => 'Save',
    'search' => 'Search',
    'select_category' => 'Select Category',
    'select_priority' => 'Select Priority',
    'shared_documents' => 'Shared Documents',
    'show_ticket' => 'Show Ticket',
    'status' => 'Status',
    'subject' => 'Subject',
    'support_ticket_categories' => 'Support Ticket Categories',
    'support_ticket_priorities' => 'Support Ticket Priorities',
    'support_tickets' => 'Support Tickets',
    'take_it' => 'Take It',
    'take_ticket' => 'Take Ticket',
    'taked' => 'Taked',
    'taked_by' => 'taked by',
    'teams' => 'Teams',
    'teams_roles' => 'Teams Roles',
    'there_are_no_tickets' => 'There are no tickets',
    'there_is_no_agent_yet' => 'There is not Agent yet.',
    'ticket_creator' => 'Ticket Creator',
    'ticket_subject' => 'Ticket Subject',
    'ticket_to_take' => 'Ticket To Take',
    'tickets' => 'Tickets',
    'tickets_description' => 'Here you can see your all tickets and below you can create a new one.',
    'type_your_message' => 'Type your message...',
    'update_category' => 'Update Category',
    'update_priority' => 'Update Priority',
    'updated' => 'Updated',
    'user_roles' => 'User Roles',
    'website' => 'Website',
    'with' => 'with',
];
