<?php

/*
|--------------------------------------------------------------------------
| Ticket Language Lines / RO
|--------------------------------------------------------------------------
|         _________  _______          _       ____  _____  ________
|        |  _   _  ||_   __ \        / \     |_   \|_   _||_   __  |
|        |_/ | | \_|  | |__) |      / _ \      |   \ | |    | |_ \_|
|            | |      |  __ /      / ___ \     | |\ \| |    |  _| _
|           _| |_    _| |  \ \_  _/ /   \ \_  _| |_\   |_  _| |__/ |
|          |_____|  |____| |___||____| |____||_____|\____||________|
|                                                      by custura.de
*/

return [
    'acent_roles' => 'Rolurile Agentului',
    'actions' => 'Actiuni',
    'agent' => 'Agent',
    'agent_roles' => 'Rolurile Agentului',
    'all_tickets' => 'Toate Tichetele',
    'all_tickets_description' => 'Aici puteți vedea sau lua orice tichet existent.',
    'approved' => 'Aprobat',
    'are_you_sure_category' => 'Sigur doriți să ștergeți această categorie?',
    'are_you_sure_priority' => 'Sigur doriți să ștergeți această prioritate?',
    'are_you_sure_you_wold_like_to_recive_this_ticket' => 'Sunteți sigur că doriți să primiți acest Tichet?',
    'by' => 'de',
    'cancel' => 'Anuleaza',
    'category' => 'Categorie',
    'category_edit' => 'Editare Categorie',
    'create' => 'Creaza',
    'create_a_new_ticket' => 'Creați un Tichet nou',
    'create_category' => 'Creați Categorie',
    'create_category_description' => 'Creați o nouă categorie de asistență.',
    'create_priority' => 'Creați Prioritate',
    'create_priority_description' => 'Creați o nouă prioritate de asistență.',
    'create_ticket' => 'Creați Tichet',
    'create_ticket_description' => 'Creați un nou tichet de asistență.',
    'created' => 'Creat',
    'delete' => 'Sterge',
    'delete_category' => 'Ștergeți Categoria',
    'delete_priority' => 'Ștergeți Prioritate',
    'deleted' => 'Sters',
    'description' => 'Descriere',
    'disapproved' => 'Dezaprobat',
    'don\'_worry' => 'nu-ți face griji, respiră adânc și spune „Bună ziua”',
    'fail_keyword' => 'Nu s-au găsit tichete care să corespundă cuvântului cheie de căutare',
    'file_upload' => 'Urca Fisier',
    'language' => 'Limba',
    'link_to_ticket' => 'Link către Tichet',
    'location' => 'Locatie',
    'manage_category' => 'Gestionați Categorii',
    'manage_category_description' => 'Aici puteți modifica categoriile existente.',
    'manage_priority' => 'Gestionați Prioritati',
    'manage_priority_description' => 'Aici puteți modifica prioritățile existente.',
    'manage_recived_tickets' => 'Gestionați tichetele primite',
    'manage_recived_tickets_description' => 'Aici puteți gestiona tichetele existente care vă aparțin.',
    'mark' => 'Marchează',
    'member_since' => 'Membru din',
    'name' => 'Nume',
    'no_message_yet' => 'Niciun mesaj încă...',
    'no_tickets_in_database' => 'Nu există tichete în baza de date',
    'priority' => 'Prioritate',
    'priority_edit' => 'Editare Prioritate',
    'reopen' => 'Redeschide',
    'save' => 'Salveaza',
    'search' => 'Cauta',
    'select_category' => 'Selecteaza Categoria',
    'select_priority' => 'Selecteaza Prioritatea',
    'shared_documents' => 'Documente partajate',
    'show_ticket' => 'Arata Tichet',
    'status' => 'Status',
    'subject' => 'Subiect',
    'support_ticket_categories' => 'Categorii de asistență',
    'support_ticket_priorities' => 'Priorități de asistență',
    'support_tickets' => 'Tichete de Asistență',
    'take_it' => 'Ia-l',
    'take_ticket' => 'Luați Tichetul',
    'taked' => 'Luat',
    'taked_by' => 'luat de',
    'teams' => 'Echipe',
    'teams_roles' => 'Rolurile in Echipă',
    'there_are_no_tickets' => 'Nu există Tichete',
    'there_is_no_agent_yet' => 'Nu există încă un Agent.',
    'ticket_creator' => 'Creatorul Tichetului',
    'ticket_subject' => 'Tichet Subiect',
    'ticket_to_take' => 'Tichet de luat',
    'tickets' => 'Tichete',
    'tickets_description' => 'Aici îți poți vedea toate Tichetele, iar mai jos poți crea unul nou.',
    'type_your_message' => 'Introduceți mesajul dvs...',
    'update_category' => 'Actualizare Categorie',
    'update_priority' => 'Actualizare Prioritate',
    'updated' => 'Modificat',
    'user_roles' => 'Rolurile Utilizatorului',
    'website' => 'Website',
    'with' => 'cu',
];
